$(document).ready(function(){
    $('.mdi-menu').click(function(){
        $('.menu-medium').hide();
        $('.menu-large').show();
        $('.content').css('margin-left','200px');
    });
    $('.mdi-backburger').click(function(){
        $('.menu-large').hide();
        $('.menu-medium').show();
        $('.content').css('margin-left','0px');
    });
    $('.backburger-small-1').click(function(){
        $('.menu-small-nav').show();
        $('.backburger-small-2').show();
        $('.backburger-small-1').hide();
    });
    $('.backburger-small-2').click(function(){
        $('.menu-small-nav').hide();
        $('.backburger-small-2').hide();
        $('.backburger-small-1').show();
    });
});